"""The nested atom family over tied groups, and the ring-cut variant of it.

Two families can represent a point of a tied face, and which one is used decides whether it certifies.

In the *single-link* family the atoms are the base support and the base plus one tied link. Their masses
are link marginals belonging to distinct atoms, so they must sum to at most one and the domain is a
product of simplices.

In the *nested* family the atoms are indexed by tied groups. A group is a tied edge, and a support admits
exactly one of its two orientations, so there is one weight per group and any weight vector in the unit
cube is realised by at most ``k + 1`` atoms. The domain is a box, which is what the cube argument needs.

Both rest on one observation: the nested family is generated by a single uniform. Draw ``U`` on the unit
interval and admit group ``i`` when ``U`` lands in a set of measure ``w_i``. The marginals depend only on
the measures, while *which* sets are used decides the joint law, and that freedom is what buys an acyclic
representation when the tied links close a ring.

    Nested            the sets are the initial segments. Nested, ``k + 1`` atoms, cyclic exactly when
                      the all-forward support is.
    Ring-cut          the sets are chosen so the ring's links are never all admitted at once. Feasible
                      when the measures leave enough room, and the support is then at most ``2k + 1``.

The two are the same routine at different sets, which is why :func:`nested_atoms` takes the ring as an
argument rather than living in a separate code path.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from ..config import WEIGHT_EPSILON

__all__ = ["TiedGroup", "RingResidual", "build_groups", "nested_atoms", "ring_feasible",
           "find_tied_cycle", "cycle_in_mask", "atom_mask", "marginals", "is_acyclic"]


@dataclass(frozen=True)
class TiedGroup:
    """One tied edge. ``forward`` is the orientation whose probability is the group's weight.

    ``reverse`` is ``None`` for a singleton group, where only one orientation is tied at all and the
    complementary branch admits nothing rather than the opposite link. Both cases are one binary choice
    with probability ``w``, which is why they share a representation.
    """

    forward: int
    reverse: int | None
    index_forward: int
    index_reverse: int | None

    @property
    def paired(self) -> bool:
        return self.reverse is not None


class RingResidual(RuntimeError):
    """A cycle survives in some atom after the ring cut has removed the one ring it covers.

    The construction is stated for a single tied ring. Two rings sharing groups would need the cut sets to
    cover the circle for each ring at once, which is neither claimed nor ruled out. When that happens the
    face is refused here rather than loaded, because loading a cyclic support silently produces a number
    that satisfies no equation of the model.
    """


def build_groups(topo, items) -> list[TiedGroup]:
    """Group one destination's tied links into edges.

    ``items`` is a list of ``(index into the tie list, link id)``. Two tied links form one group when they
    are opposite orientations of a single edge. The forward orientation is the lower link id, so the
    grouping is a function of the network and never of iteration order.
    """
    tail, head = topo.tail, topo.head
    by_edge: dict = {}
    for index, link in items:
        key = (int(min(tail[link], head[link])), int(max(tail[link], head[link])))
        by_edge.setdefault(key, []).append((int(index), int(link)))

    groups = []
    for key in sorted(by_edge):
        members = sorted(by_edge[key], key=lambda pair: pair[1])
        if len(members) == 1:
            index, link = members[0]
            groups.append(TiedGroup(link, None, index, None))
        elif len(members) == 2:
            (first_index, first), (second_index, second) = members
            groups.append(TiedGroup(first, second, first_index, second_index))
        else:
            raise ValueError(f"edge {key} carries {len(members)} tied links; "
                             f"an edge has at most two orientations")
    return groups


def _cells(intervals, k):
    """Cells of the unit interval cut at every endpoint, each labelled by the admit set holding on it.

    Membership is read at the cell midpoint, which is exact because no endpoint lies strictly inside a
    cell by construction.
    """
    cuts = {0.0, 1.0}
    for pieces in intervals:
        for low, high in pieces:
            cuts.add(float(low))
            cuts.add(float(high))
    points = sorted(c for c in cuts if -WEIGHT_EPSILON <= c <= 1.0 + WEIGHT_EPSILON)
    out = []
    for low, high in zip(points[:-1], points[1:]):
        if high - low <= WEIGHT_EPSILON:
            continue
        midpoint = 0.5 * (low + high)
        admit = np.zeros(k, dtype=bool)
        for i, pieces in enumerate(intervals):
            admit[i] = any(start <= midpoint < end for start, end in pieces)
        out.append((admit, high - low))
    return out


def _wrapped(start, length):
    """The arc of the circle beginning at ``start`` of the given length, split at the wrap point."""
    start = float(start) % 1.0
    length = float(length)
    if length >= 1.0 - WEIGHT_EPSILON:
        return [(0.0, 1.0)]
    end = start + length
    if end <= 1.0:
        return [(start, end)]
    return [(start, 1.0), (0.0, end - 1.0)]


def _complement(pieces):
    """The unit interval minus a union of half-open intervals."""
    out = []
    cursor = 0.0
    for low, high in sorted(pieces):
        if low > cursor + WEIGHT_EPSILON:
            out.append((cursor, low))
        cursor = max(cursor, high)
    if cursor < 1.0 - WEIGHT_EPSILON:
        out.append((cursor, 1.0))
    return out


def ring_feasible(w, ring) -> tuple[bool, float]:
    """Whether some coupling with these marginals leaves the ring incomplete. Returns the slack.

    A negative slack is Bonferroni's obstruction: the ring is admitted in full under *every* coupling with
    these marginals, so no acyclic representation exists at all and the face has no admissible mixture.
    That is a statement about the marginals rather than about the search, and it is the one circumstance
    in which refusing is correct.
    """
    w = np.asarray(w, dtype=float)
    admitted = np.array([w[i] if forward else 1.0 - w[i] for i, forward in ring], dtype=float)
    slack = (len(ring) - 1) - float(admitted.sum())
    return slack >= -WEIGHT_EPSILON, slack


def nested_atoms(w, ring=None):
    """The atoms and masses of the nested family, or of the ring-cut family when a ring must be avoided.

    ``w`` is one marginal per group. ``ring``, when given, is a list of ``(group index, uses_forward)``
    naming the groups whose links close a directed cycle and the orientation the cycle uses. Returns a
    list of ``(admit, mass)``, where ``admit`` says which groups take their forward orientation. Marginals
    are exact by construction rather than by fitting.

    Without a ring the sets are the initial segments, so the admit sets are nested and there are at most
    ``k + 1`` of them, with the sort induced rather than performed. With a ring, arcs whose lengths are
    the complementary probabilities are laid end to end around the circle. They cover it exactly when the
    feasibility condition holds, so every draw leaves at least one of the ring's links out and no atom
    contains the whole ring. Groups outside the ring keep their initial segments, so the family reduces to
    the nested one when the ring is empty.
    """
    w = np.asarray(w, dtype=float)
    k = int(w.shape[0])
    if k == 0:
        return [(np.zeros(0, dtype=bool), 1.0)]
    w = np.clip(w, 0.0, 1.0)
    intervals = [[(0.0, float(w[i]))] if w[i] > WEIGHT_EPSILON else [] for i in range(k)]

    if ring:
        feasible, slack = ring_feasible(w, ring)
        if not feasible:
            raise ValueError(f"the tied ring is unavoidable at these marginals, slack {slack:.3e}")
        cursor = 0.0
        for i, uses_forward in ring:
            admitted = w[i] if uses_forward else 1.0 - w[i]
            absent = _wrapped(cursor, 1.0 - float(admitted))
            cursor = (cursor + 1.0 - float(admitted)) % 1.0
            # ``absent`` is where the ring's link at this group is out. The forward orientation is
            # admitted on its complement when the ring uses forward, and on ``absent`` itself otherwise.
            intervals[i] = _complement(absent) if uses_forward else absent

    cells = _cells(intervals, k)
    total = sum(mass for _, mass in cells)
    if abs(total - 1.0) > 1e-9:
        raise AssertionError(f"atom masses sum to {total!r} rather than one")
    return cells


def _links_by_group(groups):
    """Map each tied link to the group it belongs to and the orientation it represents."""
    lookup = {}
    for index, group in enumerate(groups):
        lookup[int(group.forward)] = (index, True)
        if group.reverse is not None:
            lookup[int(group.reverse)] = (index, False)
    return lookup


def cycle_in_mask(topo, mask, groups):
    """A directed cycle inside ``mask``, reported as ``[(group index, uses_forward), ...]``, or ``None``.

    Links of the cycle belonging to no tied group are dropped from the report: they lie in the base and
    are common to every atom, so they cannot be cut. Their presence is exactly why a ring can exist
    without three tied links being consecutive.
    """
    tail, head = topo.tail, topo.head
    lookup = _links_by_group(groups)
    outgoing: dict = {}
    for link in np.flatnonzero(np.asarray(mask, dtype=bool)):
        outgoing.setdefault(int(tail[link]), []).append(int(link))

    WHITE, GREY, BLACK = 0, 1, 2
    colour: dict = {}
    entered_by: dict = {}
    for source in list(outgoing):
        if colour.get(source, WHITE) != WHITE:
            continue
        stack = [(source, iter(outgoing.get(source, ())))]
        colour[source] = GREY
        while stack:
            node, links = stack[-1]
            advanced = False
            for link in links:
                nxt = int(head[link])
                seen = colour.get(nxt, WHITE)
                if seen == GREY:
                    cycle, node_on_cycle = [int(link)], node
                    while node_on_cycle != nxt:
                        previous = entered_by[node_on_cycle]
                        cycle.append(int(previous))
                        node_on_cycle = int(tail[previous])
                    cycle.reverse()
                    reported, listed = [], set()
                    for member in cycle:
                        if member in lookup and lookup[member][0] not in listed:
                            listed.add(lookup[member][0])
                            reported.append(lookup[member])
                    return reported or None
                if seen == WHITE:
                    colour[nxt] = GREY
                    entered_by[nxt] = int(link)
                    stack.append((nxt, iter(outgoing.get(nxt, ()))))
                    advanced = True
                    break
            if not advanced:
                colour[node] = BLACK
                stack.pop()
    return None


def find_tied_cycle(topo, base_mask, groups):
    """A directed cycle among the tied links of the all-forward atom, or ``None``.

    This is a first pass and is not exhaustive. A cyclic admissible mask needs at least three tied groups
    whose links form a directed cycle, but the cycle need not use those groups' forward orientations, and
    a group that is not admitted contributes its reverse link, so an intermediate nested atom carries a
    mix of orientations and can close a ring the all-forward atom does not.
    The ladder's face builder therefore verifies every atom it builds and recovers the real ring from
    whichever atom is cyclic. This pass is kept because the all-forward atom is the cheapest place to
    look, and finding a ring here avoids building the family twice.
    """
    mask = np.asarray(base_mask, dtype=bool).copy()
    for group in groups:
        mask[group.forward] = True
        if group.reverse is not None:
            mask[group.reverse] = False
    return cycle_in_mask(topo, mask, groups)


def atom_mask(base_mask, groups, admit):
    """The link mask an atom loads: forward where admitted, reverse where not and one exists."""
    mask = np.asarray(base_mask, dtype=bool).copy()
    for index, group in enumerate(groups):
        if admit[index]:
            mask[group.forward] = True
        elif group.reverse is not None:
            mask[group.reverse] = True
    return mask


def marginals(cells, k):
    """The probability that each group takes its forward orientation, read back from the atoms."""
    out = np.zeros(k)
    for admit, mass in cells:
        out[admit] += mass
    return out


def is_acyclic(topo, mask) -> bool:
    """Whether the masked subgraph is acyclic. Nodes touching no masked link are ignored."""
    tail, head = topo.tail, topo.head
    live = np.flatnonzero(np.asarray(mask, dtype=bool))
    if live.size == 0:
        return True
    outgoing: dict = {}
    indegree: dict = {}
    nodes = set()
    for link in live:
        origin, destination = int(tail[link]), int(head[link])
        outgoing.setdefault(origin, []).append(destination)
        indegree[destination] = indegree.get(destination, 0) + 1
        nodes.add(origin)
        nodes.add(destination)
    queue = [node for node in nodes if indegree.get(node, 0) == 0]
    emitted = 0
    while queue:
        node = queue.pop()
        emitted += 1
        for nxt in outgoing.get(node, ()):
            indegree[nxt] -= 1
            if indegree[nxt] == 0:
                queue.append(nxt)
    return emitted == len(nodes)


