"""Recursive-logit network loading on an acyclic efficient support.

On the support the value function and the loading each reduce to one ordered sweep over the links, which
is back-substitution on a triangular system and costs ``O(E)`` per destination rather than the ``O(K E)``
of ``K`` synchronous Bellman sweeps.

Backward, in reverse topological order, the value function is

    V[n] = log sum over links e out of n of exp(-mu c_e + V[head(e)]),   V[d] = 0,

and forward, in topological order, node flow is distributed over the links by the logit probabilities
``P(e | n) = exp(-mu c_e + V[head(e)] - V[n])``.

The entry points differ only in where each destination's mask comes from. :func:`load` derives it from a
potential table and may cache it across outer iterations; :func:`load_parallel` derives it inside a
compiled parallel region; :func:`load_prepared` takes masks supplied
explicitly, which is what a tied face needs, since its masks are generated by no potential.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from time import perf_counter

import numpy as np

from ._compat import njit, prange
from .network import Topology
from .subnetwork import _active_for_dest_kernel, _kahn_order_kernel, active_for_dest, kahn_order

__all__ = ["LoadingReport", "absorbing", "load", "load_parallel", "load_destination",
           "load_with_masks", "load_prepared", "prepare_masks"]


@dataclass
class LoadingReport:
    """Diagnostics from one loading pass, for callers that ask for them.

    ``support_changes`` and ``flipped_flow_share`` are ``None`` when the pass could not measure them,
    which is the case on the parallel path: it rebuilds every mask inside the kernel and keeps no cache,
    so there is no previous mask to compare against. Recording zero there would read downstream as a
    support that froze immediately, which is the opposite of not having looked.
    """

    support_changes: int | None = None
    flipped_flow_share: float | None = None
    seconds: dict = field(default_factory=dict)


@njit(nogil=True)
def _value_pass(out_ptr, out_links, head, active, cost, order, d, n_nodes, mu):
    """Backward value pass in reverse topological order, so every downstream head is final on arrival."""
    value = np.full(n_nodes, -np.inf)
    value[d] = 0.0
    for i in range(n_nodes - 1, -1, -1):
        n = order[i]
        if n == d:
            continue
        largest = -np.inf
        for idx in range(out_ptr[n], out_ptr[n + 1]):
            e = out_links[idx]
            if active[e]:
                term = -mu * cost[e] + value[head[e]]
                if term > largest:
                    largest = term
        if largest == -np.inf:
            continue
        total = 0.0
        for idx in range(out_ptr[n], out_ptr[n + 1]):
            e = out_links[idx]
            if active[e]:
                total += np.exp(-mu * cost[e] + value[head[e]] - largest)
        value[n] = largest + np.log(total)
    return value


@njit(nogil=True)
def _flow_pass(out_ptr, out_links, head, active, cost, order, value, node_flow, x, n_nodes, mu):
    """Forward flow pass in topological order, accumulating link flow into ``x`` in place."""
    for i in range(n_nodes):
        n = order[i]
        entering = node_flow[n]
        if entering <= 0.0 or not np.isfinite(value[n]):
            continue
        here = value[n]
        for idx in range(out_ptr[n], out_ptr[n + 1]):
            e = out_links[idx]
            if active[e]:
                share = entering * np.exp(-mu * cost[e] + value[head[e]] - here)
                x[e] += share
                node_flow[head[e]] += share


def _ordered(topo: Topology, active: np.ndarray) -> np.ndarray:
    order, emitted = _kahn_order_kernel(topo.out_ptr, topo.out_links, topo.head, active, topo.n_nodes)
    if emitted != topo.n_nodes:
        raise RuntimeError(f"cycle in active subgraph: ordered {emitted}/{topo.n_nodes} nodes")
    return order


def load(topo: Topology, od: np.ndarray, mu: float, cost: np.ndarray, potential: np.ndarray,
         cache: dict | None = None, reuse_support: bool = False,
         report: LoadingReport | None = None) -> np.ndarray:
    """Loading at a fixed cost over every demanded destination. Returns link flows.

    ``potential`` is the cost-to-destination table whose strict decrease defines the support: free-flow
    costs give the fixed-support model, congested costs the endogenous one.

    ``cache`` reuses each destination's mask and topological order across outer iterations, and the
    re-sort is skipped whenever the mask is unchanged. ``reuse_support`` reuses them without rebuilding,
    which is correct only where the support cannot move.

    ``report``, when supplied, receives the number of links whose status changed and the share of flow
    they carried. That share is measured per destination, because a link may change status for one
    destination while carrying flow belonging to others, and taking the union across destinations
    overstates it by orders of magnitude.
    """
    x = np.zeros(topo.n_links)
    seconds = dict(support=0.0, order=0.0, value=0.0, flow=0.0)
    support_changes = 0
    flipped_flow = 0.0
    measure_flipped = report is not None

    for d in range(topo.n_zones):
        demand = od[:, d]
        if demand.sum() <= 0.0:
            continue
        cached = cache.get(d) if cache is not None else None
        changed_mask = None
        start = perf_counter()
        if cached is not None and reuse_support:
            active, order = cached
            after_support = after_order = perf_counter()
        else:
            active = active_for_dest(topo, potential[:, d], d)
            after_support = perf_counter()
            if cached is not None and np.array_equal(active, cached[0]):
                order = cached[1]
            else:
                if cached is not None:
                    changed = active != cached[0]
                    support_changes += int(np.count_nonzero(changed))
                    if measure_flipped:
                        changed_mask = changed
                order = _ordered(topo, active)
                if cache is not None:
                    cache[d] = (active, order)
            after_order = perf_counter()

        value = _value_pass(topo.out_ptr, topo.out_links, topo.head, active, cost, order,
                            d, topo.n_nodes, mu)
        after_value = perf_counter()

        node_flow = np.zeros(topo.n_nodes)
        origins = np.flatnonzero(demand > 0.0)
        node_flow[origins] = demand[origins]
        target = np.zeros_like(x) if measure_flipped else x
        _flow_pass(topo.out_ptr, topo.out_links, topo.head, active, cost, order, value,
                   node_flow, target, topo.n_nodes, mu)
        if measure_flipped:
            if changed_mask is not None:
                flipped_flow += float(target[changed_mask].sum())
            x += target
        after_flow = perf_counter()

        seconds["support"] += after_support - start
        seconds["order"] += after_order - after_support
        seconds["value"] += after_value - after_order
        seconds["flow"] += after_flow - after_value

    if report is not None:
        total = float(x.sum())
        report.support_changes = support_changes
        report.flipped_flow_share = flipped_flow / total if total > 0.0 else 0.0
        report.seconds = seconds
    return x


@njit(parallel=True)
def _load_all_kernel(out_ptr, out_links, tail, head, potential_t, cost, mu, od_t, destinations,
                     n_nodes, n_zones, zero_dep, no_thru, n_links):
    """Load every demanded destination concurrently.

    Each destination builds its own mask, order, value pass and loading into a private row.
    Destinations are independent, so summing the rows is exact and free of races. ``potential_t`` and
    ``od_t`` are transposed so that each destination's row is contiguous.
    """
    n_demanded = destinations.shape[0]
    private = np.zeros((n_demanded, n_links))
    cyclic = np.zeros(n_demanded, dtype=np.int64)
    for i in prange(n_demanded):
        d = destinations[i]
        active = _active_for_dest_kernel(tail, head, potential_t[d], d, n_zones,
                                         zero_dep, no_thru, n_links)
        order, emitted = _kahn_order_kernel(out_ptr, out_links, head, active, n_nodes)
        if emitted != n_nodes:
            cyclic[i] = 1
            continue
        value = _value_pass(out_ptr, out_links, head, active, cost, order, d, n_nodes, mu)
        node_flow = np.zeros(n_nodes)
        for o in range(n_zones):
            demand = od_t[d, o]
            if demand > 0.0:
                node_flow[o] = demand
        _flow_pass(out_ptr, out_links, head, active, cost, order, value, node_flow,
                   private[i], n_nodes, mu)
    return private, cyclic


def load_parallel(topo: Topology, od: np.ndarray, mu: float, cost: np.ndarray,
                  potential: np.ndarray) -> np.ndarray:
    """Destination-parallel counterpart of :func:`load`, exact to the last bit.

    Masks are rebuilt inside the parallel region and no cache is kept; once parallelised the rebuild is
    cheap relative to the sweeps. A cyclic support is reported rather than used, because a partially
    written order would index out of bounds.
    """
    destinations = np.flatnonzero(od.sum(axis=0) > 0.0).astype(np.int64)
    private, cyclic = _load_all_kernel(
        topo.out_ptr, topo.out_links, topo.tail, topo.head,
        np.ascontiguousarray(potential.T), cost, mu, np.ascontiguousarray(od.T), destinations,
        topo.n_nodes, topo.n_zones, topo.zero_dep_conn, topo.no_thru, topo.n_links)
    n_cyclic = int(cyclic.sum())
    if n_cyclic:
        first = int(destinations[int(np.argmax(cyclic))])
        raise RuntimeError(f"cycle in active subgraph for {n_cyclic}/{len(destinations)} "
                           f"destinations, first at destination {first}")
    return private.sum(axis=0)


def absorbing(topo: Topology, mask: np.ndarray, d: int) -> np.ndarray:
    """Copy of ``mask`` with ``d``'s outgoing links removed, whatever the supplied mask says."""
    active = np.array(mask, dtype=bool, copy=True)
    active[topo.tail == d] = False
    return active


def load_destination(topo: Topology, od: np.ndarray, mu: float, cost: np.ndarray,
                     d: int, active: np.ndarray, order: np.ndarray) -> np.ndarray:
    """One destination's loading on an explicitly supplied support."""
    value = _value_pass(topo.out_ptr, topo.out_links, topo.head, active, cost, order,
                        d, topo.n_nodes, mu)
    node_flow = np.zeros(topo.n_nodes)
    origins = np.flatnonzero(od[:, d] > 0.0)
    node_flow[origins] = od[origins, d]
    x = np.zeros(topo.n_links)
    _flow_pass(topo.out_ptr, topo.out_links, topo.head, active, cost, order, value,
               node_flow, x, topo.n_nodes, mu)
    return x


def prepare_masks(topo: Topology, od: np.ndarray, masks: dict):
    """Fix destination, absorbing mask and topological order for a mask family that will not move.

    Inside a tied-face solve only the cost changes between evaluations, so recomputing the absorbing copy
    and the order on every call dominates when one link is contested by many destinations. Raises on a
    cyclic mask, and on a demanded destination with no mask, since a silently missing destination would
    drop its demand.
    """
    prepared = []
    for d in range(topo.n_zones):
        if od[:, d].sum() <= 0.0:
            continue
        if d not in masks:
            raise KeyError(f"destination {d} carries demand but has no mask")
        active = absorbing(topo, masks[d], d)
        prepared.append((d, active, kahn_order(topo, active)))
    return prepared


def load_with_masks(topo: Topology, od: np.ndarray, mu: float, cost: np.ndarray,
                    masks: dict) -> np.ndarray:
    """Loading where every destination's support is supplied rather than derived."""
    return load_prepared(topo, od, mu, cost, prepare_masks(topo, od, masks))


def load_prepared(topo: Topology, od: np.ndarray, mu: float, cost: np.ndarray, prepared) -> np.ndarray:
    """Loading for an already-prepared mask family."""
    x = np.zeros(topo.n_links)
    for d, active, order in prepared:
        x += load_destination(topo, od, mu, cost, d, active, order)
    return x


